services:
  db-api:
    build:
      context: ./backend/DatabaseService
      dockerfile: Dockerfile
    ports:
      - 5108:8080
    depends_on:
      - db-postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
  
  search-api:  
    build:
      context: ./backend/SearchService
      dockerfile: Dockerfile
    ports:
      - 5109:8080
    depends_on:
      - db-api
  
  cleaner-api:
    build:
      context: ./backend/CleanerService
      dockerfile: CleanerService/Dockerfile
    ports:
      - 5110:8080
    depends_on:
      - db-api
    
  db-postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      
  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr
        
secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt