services:
  db-api:
    build:
      context: ./backend/DatabaseService
      dockerfile: Dockerfile
    ports:
      - 5108:8080
    depends_on:
      - db-postgres
    environment:
      - POSTGRES_HOST=db-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  search-api:  
    build:
      context: ./backend/SearchService
      dockerfile: Dockerfile
    ports:
      - 5109:8080
    depends_on:
      - db-api
  
  cleaner-api:
    build:
      context: ./backend/CleanerService
      dockerfile: CleanerService/Dockerfile
    ports:
      - 5110:8080
    depends_on:
      - db-api
    
  db-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr